# DO NOT EDIT THIS FILE!
# This file is machine-generated from ../src/openapi.yaml
openapi: 3.1.0
info:
  title: AlsoAsked
  description: |
    The AlsoAsked API allows you to manage your account, perform searches, access search history, and more.
  version: 1.0.0
  license:
    name: Proprietary
    url: https://alsoasked.com/eula
  termsOfService: https://alsoasked.com/eula
  contact:
    name: AlsoAsked Support
    email: service@alsoasked.com
    url: https://help.alsoasked.com
tags:
  - name: Account
    description: |
      Operations related to managing an account.
  - name: Search
    description: |
      Operations related to searches.
servers:
  - url: https://api.alsoasked.com/v1
    description: Live
  - url: https://sandbox-api.alsoasked.com/v1
    description: Sandbox
components:
  headers:
    X-AlsoAsked-Credits:
      description: |
        The number of credits remaining in the account.
      schema:
        type: integer
        format: int64
        minimum: 0
      example: 100
    X-RateLimit-Remaining:
      description: |
        The number of requests remaining in the current rate limit window.
      schema:
        type: integer
        format: int64
        minimum: 0
      example: 984
    X-RateLimit-Limit:
      description: |
        The maximum number of requests that can be made in the current rate limit window.
      schema:
        type: integer
        format: int64
        minimum: 0
      example: 1000
    X-RateLimit-Reset:
      description: |
        The time at which the current rate limit window resets in UTC epoch seconds.
      schema:
        type: integer
        format: int64
        minimum: 0
      example: 1672531200
  schemas:
    Account:
      title: Account
      type: object
      description: |
        The account object is returned in the response body of any request that results in the details of an account being
        returned.
      properties:
        id:
          type: string
          pattern: ^[a-zA-Z0-9]{32}$
          description: |
            The unique identifier for the account.
          example: 6G8QgoK9ar0E1pB7Rl0LN5mxljdAvBWb
        name:
          type: string
          description: |
            The human-readable name for the account.
          example: Mantis Toboggan
        email:
          type: string
          format: email
          description: |
            The email address associated with the account.
          example: mantis.toboggan@gmail.com
        plan_type:
          type: string
          description: |
            The type of plan that the account, or the account's team owner, is subscribed to.
          enum:
            - free
            - basic
            - lite
            - pro
          example: pro
        credits:
          type: integer
          format: int64
          minimum: 0
          description: |
            The number of credits remaining in the account.
          example: 100
        credit_reset_date:
          type: string
          format: date-time
          description: |
            The account credit reset date is the date and time at which the account credits will be reset to default.
          example: '2023-02-01T00:00:00Z'
        registration_date:
          type: string
          format: date-time
          description: |
            The account registration date is the date and time at which the account was registered.
          example: '2023-01-01T00:00:00Z'
      example:
        id: 6G8QgoK9ar0E1pB7Rl0LN5mxljdAvBWb
        name: Mantis Toboggan
        email: mantis.toboggan@gmail.com
        plan_type: pro
        credits: 100
        credit_reset_date: '2023-02-01T00:00:00Z'
        registration_date: '2023-01-01T00:00:00Z'
    Error:
      title: Error
      type: object
      description: |
        The error object is returned in the response body of any request that results in an error.
      properties:
        status:
          type: string
          description: |
            The error status is an identifier for the type of error that occurred.
          enum:
            - internal_server_error
            - invalid_api_key
            - missing_api_key
            - rate_limit_exceeded
            - under_maintenance
        message:
          type: string
          description: |
            A human-readable message describing the error. This message is intended to be read by a developer and is
            not suitable for display to an end user.
      example:
        status: internal_server_error
        message: An internal server error has occurred
  responses:
    Account:
      description: |
        The account object is returned in the response body of a successful request to get account information.
      headers:
        X-AlsoAsked-Credits:
          $ref: '#/components/headers/X-AlsoAsked-Credits'
        X-RateLimit-Remaining:
          $ref: '#/components/headers/X-RateLimit-Remaining'
        X-RateLimit-Limit:
          $ref: '#/components/headers/X-RateLimit-Limit'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Account'
          examples:
            Account:
              summary: Account example
              description: |
                The following example shows the response body of a successful request to get account information.
              value:
                id: 6G8QgoK9ar0E1pB7Rl0LN5mxljdAvBWb
                name: Mantis Toboggan
                email: mantis.toboggan@gmail.com
                plan_type: pro
                credits: 100
                credit_reset_date: '2023-02-01T00:00:00Z'
                registration_date: '2023-01-01T00:00:00Z'
    MissingApiKeyError:
      description: |
        The API key provided in the request header is missing. This error is returned when no API key is provided in the
        request header.
      headers:
        X-RateLimit-Remaining:
          $ref: '#/components/headers/X-RateLimit-Remaining'
        X-RateLimit-Limit:
          $ref: '#/components/headers/X-RateLimit-Limit'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            MissingApiKeyError:
              summary: Missing API key error example
              description: |
                The following example shows the response body of an unauthorized error. This error is returned when no
                API key is provided in the request header.
              value:
                status: missing_api_key
                message: No API key has been specified
    InvalidApiKeyError:
      description: |
        The API key provided in the X-Api-Key request header is invalid. This error is returned when the API key provided in
        the request header has either been deleted or doesn't exist.
      headers:
        X-RateLimit-Remaining:
          $ref: '#/components/headers/X-RateLimit-Remaining'
        X-RateLimit-Limit:
          $ref: '#/components/headers/X-RateLimit-Limit'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            InvalidApiKeyError:
              summary: Invalid API key error example
              description: |
                The following example shows the response body of an invalid API key error. This error is returned when an
                invalid API key is provided in the request header.
              value:
                status: invalid_api_key
                message: The API key provided is invalid
    RateLimitExceededError:
      description: |
        The error "maximum requests per second exceeded" occurs when the client has made too many requests in a short period
        of time.
      headers:
        X-RateLimit-Remaining:
          $ref: '#/components/headers/X-RateLimit-Remaining'
        X-RateLimit-Limit:
          $ref: '#/components/headers/X-RateLimit-Limit'
        X-RateLimit-Reset:
          $ref: '#/components/headers/X-RateLimit-Reset'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            RateLimitExceededError:
              summary: Rate limit exceeded error example
              description: |
                The following example shows the response body of a rate limit exceeded error. This error is returned when the
                client has made too many requests in a short period of time.
              value:
                status: rate_limit_exceeded
                message: The maximum number of requests per second have been exceeded
    InternalServerError:
      description: |
        An internal server error occurred. This error is returned when the server encounters an unexpected issue
        while processing the request.
      headers:
        X-RateLimit-Remaining:
          $ref: '#/components/headers/X-RateLimit-Remaining'
        X-RateLimit-Limit:
          $ref: '#/components/headers/X-RateLimit-Limit'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            InternalServerError:
              summary: Internal server error example
              description: |
                The following example shows the response body of an internal server error. This error is returned when the
                server encounters an unexpected issue while processing the request.
              value:
                status: internal_server_error
                message: An internal server error has occurred
    UnderMaintenanceError:
      description: |
        The API is currently under maintenance. This error is returned when the API is temporarily unavailable due to
        maintenance.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            UnderMaintenanceError:
              summary: Under maintenance error example
              description: |
                The following example shows the response body of an under maintenance error. This error is returned when the
                API is temporarily unavailable due to maintenance.
              value:
                status: under_maintenance
                message: The API is currently under maintenance
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-Api-Key
      description: |
        API key required to authenticate requests to the AlsoAsked API. An API key can be obtained by registering for an
        account and creating a key under the developer settings. The key must be passed in the header of each request
        with the key name `X-Api-Key`. Without an API key, all requests will be rejected.
paths:
  /account:
    get:
      operationId: getAccount
      tags:
        - Account
      summary: Get account information
      description: |
        Get information about the current user's account.
      security:
        - apiKey: []
      responses:
        '200':
          $ref: '#/components/responses/Account'
        '401':
          $ref: '#/components/responses/MissingApiKeyError'
        '403':
          $ref: '#/components/responses/InvalidApiKeyError'
        '429':
          $ref: '#/components/responses/RateLimitExceededError'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '503':
          $ref: '#/components/responses/UnderMaintenanceError'
